# Generated by Django 4.1.2 on 2022-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebadev',
            name='picture',
            field=models.FileField(upload_to='media/'),
        ),
    ]
