# Generated by Django 4.1.2 on 2022-10-19 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0002_alter_pruebadev_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='pruebaClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(default='', max_length=30)),
                ('fechaOperacion', models.DateField(default=datetime.datetime(2022, 10, 19, 17, 15, 47, 331905))),
                ('rosbag', models.FileField(upload_to='media/')),
                ('videoCliente', models.FileField(upload_to='media/')),
                ('informeCliente', models.FileField(upload_to='media/')),
                ('resultadoCliente', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='pruebaDev',
        ),
    ]
