# Generated by Django 4.1.2 on 2022-10-19 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0003_pruebaclientes_delete_pruebadev'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemploArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('archivoImg', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='pruebaclientes',
            name='fechaOperacion',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 19, 17, 37, 607507)),
        ),
    ]
