# Generated by Django 4.1.2 on 2022-10-19 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0004_ejemploarchivo_alter_pruebaclientes_fechaoperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaclientes',
            name='fechaOperacion',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 19, 37, 44, 782818, tzinfo=datetime.timezone.utc)),
        ),
    ]
