# Generated by Django 4.1.2 on 2022-10-19 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0005_alter_pruebaclientes_fechaoperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaclientes',
            name='fechaOperacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
