# Generated by Django 4.1.2 on 2022-10-26 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0006_alter_pruebaclientes_fechaoperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='inspeccionInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInspeccion', models.DateField(default=datetime.datetime(2022, 10, 26, 20, 59, 58, 346245))),
                ('unidadMinera', models.CharField(default='Antamina', max_length=64)),
            ],
        ),
    ]
