# Generated by Django 4.1.2 on 2022-10-26 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0007_inspeccioninformacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccioninformacion',
            name='fechaInspeccion',
            field=models.DateField(default=datetime.datetime(2022, 10, 26, 21, 0, 37, 675846, tzinfo=datetime.timezone.utc)),
        ),
    ]
