# Generated by Django 4.1.2 on 2022-10-26 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientTumi', '0008_alter_inspeccioninformacion_fechainspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccioninformacion',
            name='fechaInspeccion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
